name: GitHub Build
on:
  release:
    types: [published]
  workflow_call:
jobs: 
  build:    
    name: "build"
    runs-on: ubuntu-latest   
    container:      
      image: python:3.12
    timeout-minutes: 10
    steps:
      - name: checkout the git project
        uses: actions/checkout@v4
      - name: build
        run: |
          # Fix relative links for PyPi
          sed -i 's|(./|(https://github.com/StatCan/gensol-banff-processor/blob/main/|g' ./README.md
          pip install build      
          python -m build          
      - name: upload artifacts        
        uses: actions/upload-artifact@v4
        with:
          name: artifacts          
          path: |            
            dist/*.whl
